version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "main"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "builder"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "builder"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "autoupdate"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "autoupdate"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "24.04"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "24.04"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" 
    target-branch: "26.04"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "26.04"
